//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FS.Core.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FantasySportsEntities : DbContext
    {
        public FantasySportsEntities()
            : base("name=FantasySportsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NbaBoxscore> NbaBoxscores { get; set; }
        public virtual DbSet<NbaPlayer> NbaPlayers { get; set; }
        public virtual DbSet<NbaTeamStat> NbaTeamStats { get; set; }
        public virtual DbSet<Entry> Entries { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<IdentityProvider> IdentityProviders { get; set; }
        public virtual DbSet<League> Leagues { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<AppSetting> AppSettings { get; set; }
        public virtual DbSet<NbaGameLinescore> NbaGameLinescores { get; set; }
        public virtual DbSet<Period> Periods { get; set; }
        public virtual DbSet<Pick> Picks { get; set; }
        public virtual DbSet<NbaTeam> NbaTeams { get; set; }
        public virtual DbSet<vNbaGame> vNbaGames { get; set; }
        public virtual DbSet<vNbaTeamStat> vNbaTeamStats { get; set; }
        public virtual DbSet<vUser> vUsers { get; set; }
    }
}
