//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NbaBoxscore
    {
        public string GameId { get; set; }
        public int TeamId { get; set; }
        public int PlayerId { get; set; }
        public string StartPosition { get; set; }
        public string Min { get; set; }
        public Nullable<int> FGM { get; set; }
        public Nullable<int> FGA { get; set; }
        public Nullable<int> FG3M { get; set; }
        public Nullable<int> FG3A { get; set; }
        public Nullable<int> FTM { get; set; }
        public Nullable<int> FTA { get; set; }
        public Nullable<int> OREB { get; set; }
        public Nullable<int> REB { get; set; }
        public Nullable<int> AST { get; set; }
        public Nullable<int> STL { get; set; }
        public Nullable<int> BLK { get; set; }
        public Nullable<int> TOVR { get; set; }
        public Nullable<int> PF { get; set; }
        public Nullable<int> PTS { get; set; }
        public int Id { get; set; }
    }
}
