//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NbaTeam
    {
        public int Id { get; set; }
        public int TeamId { get; set; }
        public string Abbreviation { get; set; }
        public string City { get; set; }
        public string Nickname { get; set; }
        public string Arena { get; set; }
    }
}
