//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pick
    {
        public int Id { get; set; }
        public int EntryId { get; set; }
        public int PeriodId { get; set; }
        public int Value { get; set; }
    
        public virtual Entry Entry { get; set; }
        public virtual Period Period { get; set; }
    }
}
