//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vNbaGame
    {
        public int Id { get; set; }
        public string GameId { get; set; }
        public string SeasonId { get; set; }
        public System.DateTime DateTime { get; set; }
        public string PeriodValue { get; set; }
        public string PeriodStatus { get; set; }
        public string PeriodName { get; set; }
        public string GameStatus { get; set; }
        public string GameClock { get; set; }
        public int VisitorId { get; set; }
        public string VisitorScore { get; set; }
        public int HomeId { get; set; }
        public string HomeScore { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string HomeTeamAbbreviation { get; set; }
        public string HomeTeamCity { get; set; }
        public string HomeTeamNickname { get; set; }
        public string VisitorTeamAbbreviation { get; set; }
        public string VisitorTeamCity { get; set; }
        public string VisitorTeamNickname { get; set; }
    }
}
