//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FS.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vNbaTeamStat
    {
        public int Id { get; set; }
        public int TeamId { get; set; }
        public string SeasonDesc { get; set; }
        public Nullable<int> GP { get; set; }
        public Nullable<int> W { get; set; }
        public Nullable<int> L { get; set; }
        public Nullable<double> FGPCT { get; set; }
        public Nullable<double> FG3PCT { get; set; }
        public Nullable<double> FTPCT { get; set; }
        public Nullable<double> OREB { get; set; }
        public Nullable<double> REB { get; set; }
        public Nullable<double> AST { get; set; }
        public Nullable<double> STL { get; set; }
        public Nullable<double> BLK { get; set; }
        public Nullable<double> TOVR { get; set; }
        public Nullable<double> PTS { get; set; }
        public string Abbreviation { get; set; }
    }
}
